### ISSUE TITLE
What is the procedure of Bry-Boschan algorithm

### ISSUE THREAD

**Issue by zhangyw49** [LenkaV/CIF#17]
thank you for your work. 
what puzzled me is the Bry-Boschan algorithm. there are many filters such as spencer curve and MAs in the original paper. but i can't find any filters in your code. so what is your BB algorithm based on?

**Comment by LenkaV** [comment]
I use a "modified" Bry-Boschan algorithm designed for my thesis.

> The original nonparametric Bry-Boschan algorithm (Bry and Boschan, 1971) was introduced before the Hodrick-Prescott filter became widespread. Therefore, its authors had to use different smoothing methods, which tended to shift the turning points. The algorithm described by figure 4.14 assumes the usage of Hodrick-Prescott filter during the previous phases and thus uses simplified version of Bry-Boschan method, which was designed for this thesis. The simplified algorithm coincides with the rules about minimal lengths of cycles, phases, etc., which were originally introduced by Bry and Boschan.

For more information, see chapter 4.5.1 of my thesis: [vrana_CIF_2019.pdf](https://github.com/LenkaV/CIF/files/3564880/vrana_CIF_2019.pdf)

Feel free to fork the repo and add "full" Bry-Boschan algorithm into the CIF package. I believe, many researchers would appreciate it.

**Comment by zhangyw49** [comment]
ok. thank you. I am woking with the "full", Bry-Boschan algorithm code. I am glad to add it to CIF when i complete.

**Comment by LenkaV** [comment]
Thanks 👍
