### ISSUE TITLE
*** AttributeError: 'MultiIndex' object has no attribute 'labels'

### ISSUE THREAD

**Issue by sirhc78** [LenkaV/CIF#18]
Hi,
I've found a bug recently.
I use :
selection = ["USA", "EA19", "JPN", "GBR","CHE"]
data, subjects, measures = cif.createDataFrameFromOECD(countries = selection, dsname = 'MEI', frequency = 'M',startDate= '2019-09',endDate='2020-12')

And I get
Requesting URL http://stats.oecd.org/SDMX-JSON/data/MEI/USA...M/all
Data downloaded from https://stats.oecd.org/SDMX-JSON/data/MEI/USA...M/all?startTime=2019-09&endTime=2020-12&dimensionAtObservation=AllDimensions
*** AttributeError: 'MultiIndex' object has no attribute 'labels'

**Comment by LenkaV** [comment]
Thank you. I can see that .labels in pandas library was deprecated in version 0.24.0.

**Comment by LenkaV** [comment]
New version of CIF has been released (0.0.6). It works with newer version of pandas MultiIndex.
